In [1]:
import numpy
numpy.array([1,2,3,4])

array([1, 2, 3, 4])

In [2]:
import numpy as np
np.array([4,5,6,7])

array([4, 5, 6, 7])

In [3]:
from numpy import array
array([4,3,5,6])

array([4, 3, 5, 6])

In [4]:
# Import the math package
import math
# Definition of radius
r = 0.43

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r*r

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [5]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
phi = radians(12)
dist = r*phi

# Print out dist
print(dist)

40317.10572106901


In [7]:
from scipy.linalg import inv as my_inv
my_inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [10]:
# height_in is available as a regular list

# Import numpy
import numpy as np
height_in = [7,6,5.5, 6, 8]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in

print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*.0254

# Print np_height_m
print(np_height_m)

[7.  6.  5.5 6.  8. ]
[0.1778 0.1524 0.1397 0.1524 0.2032]


In [17]:
# height_in and weight_lb are available as regular lists
height_in = [74,65,78,72]
weight_lb = [180,120,160,100]
# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

[23.11037639 19.96882384 18.48965171 13.56228793]


In [18]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array

light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21

print(bmi[light])


[False  True  True  True]
[19.96882384 18.48965171 13.56228793]


In [19]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [20]:
arr = np.array([True, 1, 2])

In [21]:
print(arr)

[1 1 2]


In [22]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[2])

# Print out sub-array of np_height_in: index 100 up to and including index 110

print(np_height_in[2:4])

160
[78 72]


In [23]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [24]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [25]:
# baseball is available as a regular list of lists
baseball = [[77,100],[71,110],[65,120],[68,98]]
# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 3rd row of np_baseball
print(np_baseball[2, :])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]

# Print out height of 4th player
print(np_baseball[3, 0])

[ 65 120]
68


In [30]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np
updated = np.array([[  1.2303559,  -11.16224898     ],
 [  1.02614252,  16.09732309       ],
    [  1.1544228,    5.08167641        ],
 [  1.1544228,    5.08167641        ]])
# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 78.2303559   88.83775102]
 [ 72.02614252 126.09732309]
 [ 66.1544228  125.08167641]
 [ 69.1544228  103.08167641]]


ValueError: operands could not be broadcast together with shapes (4,2) (3,) 

In [31]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

70.25
69.5


In [33]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 70.25
Median: 69.5
Standard Deviation: 4.437059837324712
Correlation: [[ 1.         -0.59714845]
 [-0.59714845  1.        ]]


In [34]:
# heights and positions are available as lists
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]
# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gkh =  np_positions == 'GK'
gk_heights = np_heights[gkh]

# Heights of the other players: other_heights
oth =  np_positions != 'GK'
other_heights = np_heights[oth]

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 184.0
