In [12]:
import pandas as pd
df = pd.read_csv("Credit_Card.csv")
fd2 = df[['EDUCATION','MARRIAGE','AGE','BILL_AMT1']]
fd2.to_csv('creditcard.csv')


In [13]:
# Import constant from TensorFlow
from tensorflow import constant
import numpy as np
credit_numpy = fd2.to_numpy()

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)


 The datatype is: <dtype: 'float64'>

 The shape is: (30000, 4)


In [15]:
from tensorflow import Variable
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

 B1:  [1 2 3 4]


In [17]:
from tensorflow import ones_like

# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = A1*B1
C23 = A23*B23

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


In [19]:
from tensorflow import matmul

# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features,params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


In [23]:
from tensorflow import reduce_sum
#You've been given a matrix, wealth. This contains the value of bond and stock wealth 
#for five individuals in thousands of dollars.
#The first column corresponds to bonds and the second corresponds to stocks. 
#Each row gives the bond and stock wealth for a single individual. 
#Use wealth, reduce_sum(), and .numpy() to determine which statements are correct about wealth.

np_wealth = np.array([[11, 50],
 [ 7 , 2],
 [ 4, 60],
 [ 3,  0],
 [25, 10]])
wealth = constant(np_wealth)
print(wealth)
#sum of each column
print(reduce_sum(wealth,0).numpy())
# sum of each row
print(reduce_sum(wealth,1).numpy())

tf.Tensor(
[[11 50]
 [ 7  2]
 [ 4 60]
 [ 3  0]
 [25 10]], shape=(5, 2), dtype=int32)
[ 50 122]
[61  9 64  3 35]


In [2]:
import cv2
image = "signa.jpg"
imColor = cv2.imread(image,cv2.IMREAD_UNCHANGED)
imColor_resized = cv2.resize(imColor,(28,28))
imgGrey = cv2.imread(image, cv2.IMREAD_GRAYSCALE)
imgGrey_resized = cv2.resize(imgGrey,(28,28))
print(imgGrey.shape)
print(imgGrey_resized.shape)
print(imColor.shape)
print(imColor_resized.shape)
print(type(imgGrey_resized))

(183, 275)
(28, 28)
(183, 275, 3)
(28, 28, 3)
<class 'numpy.ndarray'>


In [5]:
from tensorflow import reshape
# Reshape the grayscale image tensor into a vector
gray_tensor = imgGrey_resized
color_tensor = imColor_resized
gray_vector = reshape(gray_tensor, (784, 1))

# Reshape the color image tensor into a vector
color_vector = reshape(color_tensor, (2352, 1))
print(type(gray_vector))
print(type(color_vector))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [9]:
from tensorflow import Variable
from tensorflow import GradientTape
from tensorflow import multiply


def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = Variable(x0)
	with GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y =multiply(x,x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


In [20]:
from tensorflow import matmul
from tensorflow import reshape
from tensorflow import constant
from tensorflow import reduce_sum


model = constant([[ 1.0,  0.0, -1.0]])
letter = constant([[1.0, 0.0, 1.0],
 [1.0, 1.0, 0.0],
 [1.0, 0.0, 1.0]])

# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())
print(type(prediction))
print(type(prediction.numpy()))

1.0
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.float32'>
